### ISSUE TITLE
WIP (40537): Android Manifest Permissions Out Of Place 

### ISSUE THREAD

**Issue by kirasoft** [Marketing-Suite/android-sdk#16]
Whenever I integrate the sdk with our project,  there are manifest merge conflicts. 

I did some investigating and I found that the Internet Permission is not in the correct scope. It should be declared outside of the application scope within the manifest.  
Take a look at this file 
https://github.com/Marketing-Suite/android-sdk/blob/master/EMSMobileSDK/src/main/AndroidManifest.xml  . 
The code on line 7 should be above line 3 inside of the manifest but outside of the application. 
I changed it on a local copy I have, and it worked successfully after that change.

**Comment by ClientDeveloperRelations** [comment]
Hi @kirasoft, I'll be taking a look at this, and updating as needed shortly.  Thank you for the message!

**Comment by ClientDeveloperRelations** [comment]
Fixed in 1.3.1.  Please confirm and re-open as necessary.  Thank you @kirasoft!
