### ISSUE TITLE
WIP (38958) Android - Experian SDK V2  - PRID change observed on second launch of same app in the device. 

### ISSUE THREAD

**Issue by rjambula** [Marketing-Suite/android-sdk#8]
Steps to reproduce:
1. Install App 1 and launch, check app logs with filter PUSH, PRID and token will be displayed with "experian push" tag.
2. A push can be sent for this PRID/device token.

3. Install App 2  , launch the app- wait till PRID and token will be displayed in the app.. 
4. close the App 2 and launch again.. wait for PRID.. it could be different..

To repeat, uninstall both apps and repeat the steps..

Below logs captured during QA testing: (Both of these PRIDs in production marketing suite, may give some clue)

06-07 16:55:57.471 4685-5962/? D/EXPERIANPUSH.........: App ID :393f1454-c363-46bf-a19e-5bfa902b3d04

06-07 16:55:57.471 4685-5962/? D/EXPERIANPUSH.........: Region ID :NORTH_AMERICA

06-07 16:55:57.471 4685-5962/? D/EXPERIANPUSH.........: Customer ID :663

06-07 16:56:07.471 4685-5962/? D/EXPERIANPUSH.........: PR ID :af87847f-4050-44ac-af24-25d4090860dc

06-07 16:56:07.471 4685-5962/? D/EXPERIANPUSH.........: Token  ID :eATWJpnOWk0:APA91bFkrfYP2SdnsLEKY5FL73ks2qbKxmuhHpYL7evuNKLOLVOWT63LJUtVT3StD0Jz0NmLOw675OlVCH25t17o4QcAuD9r6HfEY8wMuotenN8Sb3tnfZQ9YXYX-zhPfUyGyoCVDwHT

Sent a push but not received, so launched again.

06-07 16:57:25.351 6350-6467/? D/EXPERIANPUSH.........: App ID :393f1454-c363-46bf-a19e-5bfa902b3d04

06-07 16:57:25.351 6350-6467/? D/EXPERIANPUSH.........: Region ID :NORTH_AMERICA

06-07 16:57:25.351 6350-6467/? D/EXPERIANPUSH.........: Customer ID :663

06-07 16:57:35.351 6350-6467/? D/EXPERIANPUSH.........: App ID :393f1454-c363-46bf-a19e-5bfa902b3d04

06-07 16:57:35.351 6350-6467/? D/EXPERIANPUSH.........: Region ID :NORTH_AMERICA

06-07 16:57:35.351 6350-6467/? D/EXPERIANPUSH.........: Customer ID :663

06-07 16:57:45.351 6350-6467/? D/EXPERIANPUSH.........: PR ID :f56c9c36-57e0-4e3a-a6a5-0e0a37c8576d

06-07 16:57:45.351 6350-6467/? D/EXPERIANPUSH.........: Token  ID :eN_VqHkPX98:APA91bHJDYY1Kbefp74Upn47Bovxq4vd2-vGEU60DIsnY9Uk2L0B-ShoNY0N8Lp8FZQ24F95QvNwV-i13dAzx-AxbPWkucUvPBjc3Qyxc8nKxsgVmtgp9TfkuQw24-67LBeaiYUWkxpO

**Comment by rjambula** [comment]
[PRID change APKs.zip](https://github.com/Marketing-Suite/android-sdk/files/1072611/PRID.change.APKs.zip)

**Comment by rjambula** [comment]
Updated by Ravi on 06/16 - 

Miami Herald - Production Marketing suite.

Installed and launched app:
PR ID - d120a51d-55eb-41e1-b98f-ab639874b4eb
Device Token -
 fCu8wvKWoDQ:APA91bGGVjsSJcmYi7CtkEbBTZaT3Th7p8Wbes0OwAaXkAfIwG85r2EN-6OtehhdQAZDZjbXeQc6Q9Eyewgkq5ftqMx9zLfoQfEUc90Nnzkq4bZAGVOEj1KUTSqluviDTnabHINnWLRK

Same app launched again.
06-15 18:32:07.661 23843-24038/com.herald.newsapp D/EXPERIANPUSH.........: App ID :c0457f46-b360-4ae9-b796-9a2a24557d1e
06-15 18:32:07.661 23843-24038/com.herald.newsapp D/EXPERIANPUSH.........: Region ID :NORTH_AMERICA
06-15 18:32:07.661 23843-24038/com.herald.newsapp D/EXPERIANPUSH.........: Customer ID :663
06-15 18:33:07.811 23843-24038/com.herald.newsapp D/EXPERIANPUSH.........: PR ID :d2f3b140-2238-4c92-9d0b-4342ed3a892a
06-15 18:33:07.811 23843-24038/com.herald.newsapp D/EXPERIANPUSH.........: Token  ID :ckNM-HAIQyk:APA91bEjztG9WW901G37rPoJp923bsCEsXxjVqEikpmZFr9bolZCn_9nEUd1lrUpU3ksidnzqa87vqvgm7M_9XKVKC8cQ-sYC6GUCU_z01g26OxR72QaY8KKTJI0QEDhWrodYUa29d9K


Dev App - Sandbox environment.
Installed and launched app:
06-16 10:22:45.541 31616-1265/com.mcclatchy.dev.android D/EXPERIANPUSH.........: App ID :b40c62f3-9a9c-4e73-8ad6-56035e8d9011
06-16 10:22:45.541 31616-1265/com.mcclatchy.dev.android D/EXPERIANPUSH.........: Region ID :NORTH_AMERICA_SANDBOX
06-16 10:22:45.541 31616-1265/com.mcclatchy.dev.android D/EXPERIANPUSH.........: Customer ID :121
06-16 10:22:55.541 31616-1265/com.mcclatchy.dev.android D/EXPERIANPUSH.........: PR ID :2bb13f3b-36c1-4e72-9818-606a39addc60
06-16 10:22:55.541 31616-1265/com.mcclatchy.dev.android D/EXPERIANPUSH.........: Token  ID :dBuLBaPuG-8:APA91bFajjaHKiNtmm72MMUM6ntIXXeX7Qd8q6jPmSceI68jEsuKxgMuYGHQMhQKp7a9D2BsT80s9h9Jo7jGpnNRxrOjbyjkIZhcfU2xFFo2QvE4nO1KfrwAPp4NMhKEaBRtcECZGvcv
06-16 10:24:08.021 31616-31616/com.mcclatchy.dev.android D/MI Dev App - UALib: RichPushManager - Starting update service.

Same app launched again.
06-16 10:24:42.521 4455-4924/com.mcclatchy.dev.android D/EXPERIANPUSH.........: App ID :b40c62f3-9a9c-4e73-8ad6-56035e8d9011
06-16 10:24:42.521 4455-4924/com.mcclatchy.dev.android D/EXPERIANPUSH.........: Region ID :NORTH_AMERICA_SANDBOX
06-16 10:24:42.521 4455-4924/com.mcclatchy.dev.android D/EXPERIANPUSH.........: Customer ID :121
06-16 10:24:52.521 4455-4924/com.mcclatchy.dev.android D/EXPERIANPUSH.........: PR ID :27821939-c54c-4d75-981c-70600a940caf
06-16 10:24:52.521 4455-4924/com.mcclatchy.dev.android D/EXPERIANPUSH.........: Token  ID :f-NCCSgaCwg:APA91bGMULV7sfXGOjM-2W3DL9CmKshvqEgHlzaQ-7_BtBoCXQcD2SyFYksYzW2IJ2UiFkSITDg5RaUGQM3MJprNapH0JqedFjtCyY2_VwAJqEcG2IIkUu0E80Okba8kxLZmDjxNsA0q

For both logs, records exists in respective marketing suite.

**Comment by rjambula** [comment]
observed on 06/19 with centerdaily app.

06-19 11:21:36.329 10340-10463/com.centredaily.android D/EXPERIANPUSH.........: App ID :88ec875b-9b3c-4448-9f9f-f6e5b8d5f9e8
06-19 11:21:36.329 10340-10463/com.centredaily.android D/EXPERIANPUSH.........: Region ID :NORTH_AMERICA
06-19 11:21:36.329 10340-10463/com.centredaily.android D/EXPERIANPUSH.........: Customer ID :663
06-19 11:21:46.329 10340-10463/com.centredaily.android D/EXPERIANPUSH.........: PR ID :a15a8cc1-f0e0-48ed-9d96-415f1e35395f
06-19 11:21:46.329 10340-10463/com.centredaily.android D/EXPERIANPUSH.........: Token  ID :cGsjEQtWMH4:APA91bHHfZOTth8mqm6Ne2zsqvYWpZpllyl0bePEfqdigLn1ahH1fOO_Md5EtxOCg948b1rZhVu9iUSpZF0MokMheWzbq4VZmJ8vCMQbbyqB7mOWmEcirZ-aAbYlj1hE_Pw_ekpcNNJW

06-19 11:22:45.177 11850-11982/com.centredaily.android D/EXPERIANPUSH.........: App ID :88ec875b-9b3c-4448-9f9f-f6e5b8d5f9e8
06-19 11:22:45.177 11850-11982/com.centredaily.android D/EXPERIANPUSH.........: Region ID :NORTH_AMERICA
06-19 11:22:45.177 11850-11982/com.centredaily.android D/EXPERIANPUSH.........: Customer ID :663
06-19 11:22:55.176 11850-11982/com.centredaily.android D/EXPERIANPUSH.........: PR ID :d313d9bf-83b6-4cf4-ae4a-03d98cc05de4
06-19 11:22:55.176 11850-11982/com.centredaily.android D/EXPERIANPUSH.........: Token  ID :cgGwE9cwGMw:APA91bGWS2r37v3cFV0EFw9zCyAH7IofXYA8Ir7Z6Wp5U7PaMxqSjziK2mPZzil4i96vjCQWao6ToLYYWHjHH8ZGk_ag7xLi1irW6mxWoN434zeek752rTtFFPF3_3Y6ZIfZgei33f5O

**Comment by ClientDeveloperRelations** [comment]
Notes from meeting: Install first app, install second app, make sure second app is different in separate tests - this may cause this issue to come up more frequently.

**Comment by levl289** [comment]
@rjambula, below are the steps which I took:

1. downloaded both .apk files via filebrowser
1. started _Belleville News-Democrat_ - observed PRID & token
1. started _The Charlotte Observer_ - observed PRID & token
1. force-quit _The Charlotte Observer_
1. launch _The Charlotte Observer_ - observed PRID & token

I performed all of these in different order, and each time the PRID and token remained the same.  Additionally, after sending a test push notification (and receiving it), I started the application (which was closed), and noted the PRID and token being the same.

I'm performing this on a Nexus 6 running Android 7.0

It's perfectly normal for the PRID and the underlying token to change upon reinstallation of the application on the same device, this is a known behavior, and is not a bug.

**Comment by levl289** [comment]
TODO: QA to test on multiple devices.

**Comment by rjambula** [comment]
To reproduce:
1. Install the charlotte observer app, launch it, note the PRID.
2. relaunch the app, there could be a different PR id and device token. 
3. else uninstall and install again. repeat the steps.
[Charlotteobserver.zip](https://github.com/Marketing-Suite/android-sdk/files/1137616/Charlotteobserver.zip)



I checked in 3 different devices and observed multiple times.

**Comment by rjambula** [comment]
McClatchy QA verified and did not observe PRID change with SDK 1.2.1. 

Updated by Ravi.
